---
title: "Class 12: Genome Informatics Homework"
author: "Allen (A16897142)"
format: pdf
toc: true
---

```{r}
genotype_results <- read.table("https://bioboot.github.io/bimm143_S25/class-material/rs8067378_ENSG00000172057.6.txt", 
                               header = TRUE, 
                               sep = "", 
                               stringsAsFactors = TRUE)
head(genotype_results)
```
To find the sample size per genotype:
```{r}
table(genotype_results$geno)
```
To find the corresponding median expression levels for genotype:
```{r}
bp <- boxplot(exp ~ geno, data = genotype_results,
              main = "Expression by Genotype",
              xlab = "Genotype",
              ylab = "Expression Level",
              col = c("lightblue", "lightgreen", "lightcoral"))
```
```{r}
data.frame(Genotype = levels(genotype_results$geno), Median = bp$stats[3, ])
```
The genotype G/G has a higher expression level compared to A/A. It shows that SNP affects the expression level of ORMDL3.


